### ISSUE TITLE
Silly questions, how do you add a new project?

### ISSUE THREAD

**Issue by mingfang** [Tanaguru/Tanaguru#123]
I created a Dockerfile to run Tanaguru inside Docker https://github.com/mingfang/docker-tanaguru
I was able to login to Tanaguru but how do I create a new project after logging in?

I even signup for the Free trial to the SaaS version but didn't see a way to create a new project.

**Comment by cr2a-graphique** [comment]
Clic on action button
![Uploading action.png…]()
then 
![add](https://cloud.githubusercontent.com/assets/8180679/9899441/227557be-5c5a-11e5-83bb-703665bfb83d.png)
Choice option and create
Enjoy

**Comment by mingfang** [comment]
Thanks for the response.
In case anyone is interested, after adding a "contract"/project, you must log out and then log back in to see it in your list.
Very bad user experience but it works.

**Comment by jkowalczyk** [comment]
Hi, 

It's true, it's bad  in terms of user experience. It may be corrected in a future release. It is due to the use of a bad usage of cache for requests.
Thanks for the feedback.

Jerome
