### ISSUE TITLE
In Results page, rule description is always in French

### ISSUE THREAD

**Issue by mingfang** [Tanaguru/Tanaguru#125]
When looking at the Audit Results page, the rule description is always in French, even when the rest of the page is in English.

<img width="476" alt="screen shot 2015-09-16 at 4 00 19 pm" src="https://cloud.githubusercontent.com/assets/821695/9916755/134a0532-5c8c-11e5-9fce-eb1834fb25e5.png">

**Comment by fhalna** [comment]
@mingfand if you want a full english application you need to use AW2.2 referential.
RGAA3 is the last french referential (including HTML5 ARIA elements) but there is no translation for the moment.

**Comment by mingfang** [comment]
@fhalna thanks. I will use AW2.2.

**Comment by fhalna** [comment]
we also open a https://crowdin.com/project/ to a collaborative translation of RGAA3.
