### ISSUE TITLE
All feedback in French

### ISSUE THREAD

**Issue by robfentress** [Tanaguru/Tanaguru#134]
Even when the interface is English, the feedback given is in French.  Clicking the En link has no effect on this.  
![tanaguru-en](https://cloud.githubusercontent.com/assets/9356499/12752561/1d9d8fbe-c991-11e5-81f6-b0122d146470.PNG)

**Comment by mkebri** [comment]
Thank you for your feedback, 
actually we see that, because the RGAA3 is French referential and it was not yet translated in Tanaguru, if you want to contribute we have a project in this purpose:  https://crowdin.com/project/tanaguru 

Best regards
Tanaguru Team

**Comment by fhalna** [comment]
Hi,

Accessibility latest French standards was not translated by governement. If you want to access a full english ihm,  select Accessiweb Referential before launch audit.

![image](https://cloud.githubusercontent.com/assets/6985165/12752997/4e76b6d6-c9c5-11e5-8c99-2ce7f6bf4c5b.png)

![image](https://cloud.githubusercontent.com/assets/6985165/12753068/a566c3f0-c9c5-11e5-8f51-1417ee8db2c1.png)

**Comment by robfentress** [comment]
I don't see this available from the demo site.  Is it available there?

On Tue, Feb 2, 2016 at 9:57 AM, halna <notifications@github.com> wrote:

> Hi,
>
> Accessibility latest French standards was not translated by governement.
> If you want to access a full english ihm, select Accessiweb Referential
> before launch audit.
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/6985165/12752997/4e76b6d6-c9c5-11e5-8c99-2ce7f6bf4c5b.png>
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/6985165/12753068/a566c3f0-c9c5-11e5-8f51-1417ee8db2c1.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Tanaguru/Tanaguru/issues/134#issuecomment-178616069>.
>



-- 
Robert Fentress
Senior Accessibility Solutions Designer
540.231.1255

Technology-enhanced Learning & Online Strategies
Assistive Technologies
1180 Torgersen Hall
620 Drillfield Drive (0434)
Blacksburg, Virginia 24061

**Comment by fhalna** [comment]
Yes, i  make this screenshot from a demo account.
I check your account to give you some new trial. tell me if it's working.

**Comment by fhalna** [comment]
what's your account name ?
can you send me your email to support.tanaguru@oceaneconsulting.com ?

**Comment by vgarmash** [comment]
Here is the suggestion for you, @mkebri,  how to fix the issue while we are waiting on a translation:
set Accessiweb as a default for people who chosen English and Spanish for their website language, and set to RGAA for those who have chosen French. This way it will work intuitively. Current issue happens because the Level selection is hidden under advanced button and people don't realize that it is there.

**Comment by fhalna** [comment]
thanks @vgarmash ! translation should be online next week !  We will improve the UI to display the referential, we appreciate your advice.

**Comment by fhalna** [comment]
@vgarmash @robfentress We pushed a first english version of RGAA referential. We worked only on automated rules for the moment. Enjoy ! we are waiting  feedback or contribution if necessary.

**Comment by vgarmash** [comment]
It is kinda hard to give you feedback as you have no Contact Us form on the website ;). I also can't figure out how to re-run the audit for my site that I added during the registration. Currently I see "Your contract has expired. Please contact us if you wish to extend your use of this domain."

You know, seems like you are too focused on scanning part and didn't care much about the entry path for your users. I will wait for another year to see if you get better...

**Comment by fhalna** [comment]
Thank's for you feedback, but I need to sleep sometimes ;)

In noticed to create a contact form on my.tanaguru.com or redirect the user to [Contact](http://www.tanaguru.com/fr/contact/)

I Give you some extraball, enjoy !

**Comment by fhalna** [comment]
Done !
