### ISSUE TITLE
Assisted Audit : cannnot export manual audit after saving

### ISSUE THREAD

**Issue by CarineAM** [Tanaguru/Tanaguru#141]
When running an assisted audit, the exported file (ODS / CSV / PDF) doesn't show the manual updated criteria results. It always shows the initial audit results (before manual update).

**Comment by fhalna** [comment]
We will check this issue this week ! thank's for the feedback.

**Comment by molikathai** [comment]
Hi @CarineAM, 
At the moment, after having filtered your results, you can use your browser's printing functionality (Ctrl + P on Windows or Cmd + P on Mac OSX) to export the updated results in PDF. 
Depending on how you plan to use your results, it might help you fix your problem.
