### ISSUE TITLE
Test 11.1.3 : aria-labelledby multiple [Fr]

### ISSUE THREAD

**Issue by Shnoulle** [Tanaguru/Tanaguru#144]
Bonjour,

Sur un test : mon formulaire ne passe pas le RGAA sur le critère 11.1.3

> Test 11.1.3 : Chaque champ de formulaire associé à une étiquette via la propriété ARIA aria-labelledby, >vérifie-t-il ces conditions ?
>
>    l'étiquette possède un attribut id
 >   La valeur de l'attribut id est unique
>    La valeur de la propriété ARIA aria-labelledby est égale à la valeur de l'attribut id de l'étiquette

En fait, c'est parceque j'ai 2 identifiant dans aria-labelledby

Ma page (simplifiée)

````
<div  id="question1" class="question-wrapper text-short" data-code='T' >
	<div class="question-text">
		
		<span class='qnumcode'> T</span>
		<label for="answer69285X1X1" id="maccess-text-1" class="maccess-labelid maccess-text">Zone de texte court</label>
	</div>
	<div class='question-help clearfix'><div id="maccess-questionhelp-1" class="maccess-labelid maccess-questionhelp">Texte d'aide</div></div>
	<div class="help-wrapper">
		
		
		
	</div>
	<div class="answers-wrapper clearfix"><p class="question answer-item text-item  maxchars maxchars-8">
	<input class="text " type="text" size="50" name="69285X1X1" id="answer69285X1X1" value="" maxlength="8" onkeyup="checkconditions(this.value, this.name, this.type)" aria-labelledby="maccess-text-1 maccess-questionhelp-1"></p>

</div>
````

Si le RGAA parle d'étiquette simple , les lecteurs d'écrans reconnaissent bien les étiquettes multiples (multiple labelledby). J'ai d'autres problème sur la page, mais celui-ci ne me semble pas en echec.

Une erreur de ma part ou une erreur du coté de Tanagurui ?

ref:
- https://developer.mozilla.org/fr/docs/Accessibilit%C3%A9/ARIA/Techniques_ARIA/Utiliser_l_attribut_aria-labelledby
- https://www.w3.org/TR/wai-aria/states_and_properties#aria-labelledby

**Comment by fhalna** [comment]
Je vais regarder ça, mais c'est de précieux retours.

Un grand merci.
Je vous tient informé de l'évolution de la prise en compte de ce critère...




On Tue, May 31, 2016 at 7:44 PM, Denis Chenu < notifications@github.com [notifications@github.com] > wrote:
Bonjour,

Sur un test : mon formulaire ne passe pas le RGAA sur le critère 11.1.3

Test 11.1.3 : Chaque champ de formulaire associé à une étiquette via la propriété ARIA aria-labelledby, >vérifie-t-il ces conditions ?

l'étiquette possède un attribut id
La valeur de l'attribut id est unique
La valeur de la propriété ARIA aria-labelledby est égale à la valeur de l'attribut id de l'étiquette

En fait, c'est parceque j'ai 2 identifiant dans aria-labelledby

Ma page (simplifiée)

<div  id="question1" class="question-wrapper text-short" data-code='T' >
    <div class="question-text">

        <span class='qnumcode'> T</span>
        <label for="answer69285X1X1" id="maccess-text-1" class="maccess-labelid maccess-text">Zone de texte court</label>
    </div>
    <div class='question-help clearfix'><div id="maccess-questionhelp-1" class="maccess-labelid maccess-questionhelp">Texte d'aide</div></div>
    <div class="help-wrapper">



    </div>
    <div class="answers-wrapper clearfix"><p class="question answer-item text-item  maxchars maxchars-8">
    <input class="text " type="text" size="50" name="69285X1X1" id="answer69285X1X1" value="" maxlength="8" onkeyup="checkconditions(this.value, this.name, this.type)" aria-labelledby="maccess-text-1 maccess-questionhelp-1"></p>

</div>


Si le RGAA parle d'étiquette simple , les lecteurs d'écrans reconnaissent bien les étiquettes multiples (multiple labelledby). J'ai d'autres problème sur la page, mais celui-ci ne me semble pas en echec.

Une erreur de ma part ou une erreur du coté de Tanagurui ?

ref:

 * https://developer.mozilla.org/fr/docs/Accessibilit%C3%A9/ARIA/Techniques_ARIA/Utiliser_l_attribut_aria-labelledby [https://developer.mozilla.org/fr/docs/Accessibilit%C3%A9/ARIA/Techniques_ARIA/Utiliser_l_attribut_aria-labelledby]
 * https://www.w3.org/TR/wai-aria/states_and_properties#aria-labelledby [https://www.w3.org/TR/wai-aria/states_and_properties#aria-labelledby]

**Comment by Shnoulle** [comment]
Attention : peut être que le RGAA ne le prend pas réellement en compte les identifiants multiples. Rien de sur.

Merci :)

**Comment by fhalna** [comment]
le RGAA demande :
§  Test 11.1.1 : Chaque champ de formulaire<http://rgaa.tanaguru.com/fr/glossaire.html#champ-de-saisie-de-formulaire> vérifie-t-il une de ces conditions ?
·       Le champ de formulaire possède un attribut title
·       Une étiquette<http://rgaa.tanaguru.com/fr/glossaire.html#tiquette-de-champs-de-formulaire> (balise label) est associée au champ de formulaire
·       Le champ de formulaire<http://rgaa.tanaguru.com/fr/glossaire.html#champ-de-saisie-de-formulaire> possède une propriété aria-label
·       Le champ de formulaire<http://rgaa.tanaguru.com/fr/glossaire.html#champ-de-saisie-de-formulaire> possède une propriété aria-labelledby référençant un passage de texte identifié

donc une propriété aria-labelledby, qui peut être composée de deux références.

On implémente !

Frédéric Halna
Consultant Accessibilité Numérique
Océane Consulting
www.tanaguru.com
8 rue de Choiseul 75002 Paris
06 21 22 67 32

De : Denis Chenu [mailto:notifications@github.com]
Envoyé : mercredi 1 juin 2016 08:55
À : Tanaguru/Tanaguru
Cc : Frédéric HALNA; Comment
Objet : Re: [Tanaguru/Tanaguru] Test 11.1.3 : aria-labelledby multiple [Fr] (#144)


Attention : peut être que le RGAA ne le prend pas réellement en compte les identifiants multiples. Rien de sur.

Merci :)

**Comment by fhalna** [comment]
Done in the last version
