### ISSUE TITLE
RGAA 3.0 2016 ?

### ISSUE THREAD

**Issue by DVD27** [Tanaguru/Tanaguru#146]
Hello,

I have install my own server Tanaguru and I was surprise because I can't see RGAA3.0 2016 in the different list : 
![capture](https://user-images.githubusercontent.com/8726581/28575466-4696a108-7151-11e7-832a-60a603f43f25.PNG)
![sans titre](https://user-images.githubusercontent.com/8726581/28575474-4af30e94-7151-11e7-9ee1-f0f64c07d74d.png)

Should have a special configuration to enable it ?
Or it's enable by default in RGAA3.0 ?

**Comment by mkebri** [comment]
Hello,

To solve this problem, you must execute sql scripts manually, to add the new Rgaa 3 2016 to your database: these scripts are located (follow both links):

https://github.com/Tanaguru/Tanaguru/blob/master/rules/rgaa3-2016/src/main/resources/sql/rgaa3-2016-insert.sql

https://github.com/Tanaguru/Tanaguru/blob/master/rules/rgaa3-2016/src/main/resources/sql/rgaa3-2016-update.sql

Cordially
Tanaguru Team

**Comment by DVD27** [comment]
Thank you for your answer. 
I will try this ;)
