### ISSUE TITLE
Tanaguru install on Ubuntu

### ISSUE THREAD

**Issue by BIGANDYT** [Tanaguru/Tanaguru#151]
Hi there, im trying to install tanaguru and hitting an issue.
When installing the install file it encounters a couple of errors in the following file

/opt/tanaguru-5.1.0.i386/install/rules/sql/rgaa3-2016-insert.sql

The first issue I got around by setting sql mode to blank temporarily
The second issue im facing is the following, and not managed to get past that yet

ERROR 1054 (42S22) at line 4435: Unknown column 'Cd_Rgaa32016' in 'field list'

I am using ubuntu 16 and mysql 5.7 (i have sonarqube installed and that needs 5.6+)

I can see that in the install files you use mysql 5.5 im guessing the newer version is the issue, but has anyone managed to install on 5.7?

**Comment by BIGANDYT** [comment]
issue seems to be that the create tables script

tanaguru-20-create-tables.sql 
Creates ACCEDEWEB with a column Cd_Rgaa3
But the rules script
rgaa3-2017-insert.sql
tries to insert into Cd_Rgaa32006

Im going to try editing the rules sql and remove 2006

**Comment by BIGANDYT** [comment]
That worked but now there seems to be an issue with the war.
The install documentation omits that you need --tag_version to be specified.
But it doesnt seem to be utilised by the war installation part.
A quick fix to address this is to just rename the war
sudo mv "/opt/tanaguru-5.1.0.i386/install/web-app/tgol-web-app-5.1.0.war" "/opt/tanaguru-5.1.0.i386/install/web-app/tgol-web-app-.war"

**Comment by mkebri** [comment]
Hi,
Indeed, with the release of Rgaa32017 we renamed, in the table "ACCEDEWEB", the colomne "Cd_Rgaa32016" by "Cd_Rgaa3" an update script has been provided.

For the installation script the version is hard coded, for the moment, it's for this reason that the technical documentation has not been updated yet.

Very soon a new version of Tanaguru will come out and the raised point will be corrected. 

Thank you for your feedback.

cordially
