### ISSUE TITLE
Incorrect <nav> tag hierarchy identification

### ISSUE THREAD

**Issue by Braindead81** [Tanaguru/Tanaguru#153]
In my RGAA3 online audit i have this error:
"La valeur navigation de l'attribut role doit être dans une balise nav :"

But in the source code the navigation role is into a <nav> tag

` <nav id="navigation"> 
      <div class="menu-reponsive adm_theme-processed"> 
        <img class="header__logo-image" alt="Accueil" src="/sites/maires81.asso.fr/www.maires81.asso.fr/themes/adm81/images/responsive-menu-icon.svg" />
         menu 
      </div> 
      <div class="region region-navigation"> 
        <div role="navigation" class="block block-menu main-menu sticky-menu first last odd" id="block-menu-menu-menu-principal"> `

Others warning are true however.

**Comment by fhalna** [comment]
You have a nav tag with a child div tag, the later having a role="navigation" attribut.
Since the nav tag is present, you can't apply the role="navigation" to the div tag, it should be applied to the nav tag instead.
