### ISSUE TITLE
Error with w3cValidator json parser

### ISSUE THREAD

**Issue by trzepiz** [Tanaguru/Tanaguru#162]
tail -f /var/log/tanaguru/tanaguru.log
```
18-06-2019 10:06:10:706 5637398 ERROR org.tanaguru.analyser.AnalyserImpl  - ************************************
18-06-2019 10:06:10:706 5637398 ERROR org.tanaguru.analyser.AnalyserImpl  - error with w3cValidator json parser
18-06-2019 10:06:10:706 5637398 ERROR org.tanaguru.analyser.AnalyserImpl  - ************************************
```

How can I add w3cValidator ?
Any documentation ?

**Comment by rcharre** [comment]
Hi,

Thank you for your feedback on this, I just updated the doc : https://tanaguru.readthedocs.io/en/develop/prerequisites-webapp-doc/#w3c-validator

Regards,

Raphael Charre - Tanaguru team

**Comment by trzepiz** [comment]
Hi, 
I think that it still needs to be changed tanaguru.conf
`w3cValidatorHome=/opt/w3cValidator`
But after change, I still have ERROR 

```
19-06-2019 11:21:09:953 1191842 ERROR org.tanaguru.analyser.AnalyserImpl  - ************************************
19-06-2019 11:21:09:954 1191843 ERROR org.tanaguru.analyser.AnalyserImpl  - error with w3cValidator json parser
19-06-2019 11:21:09:954 1191843 ERROR org.tanaguru.analyser.AnalyserImpl  - ************************************

```

**Comment by rcharre** [comment]
Hi,

Did you restart tomcat after modifying the file ?
Sorry to ask for this kinds of mistakes but I don't really know why you are experimenting this issue.

Regards,

Raphael Charre - Tanaguru team

**Comment by trzepiz** [comment]
Ok. It's my foult.
After restart tomcat i don't see any error w3cvalidator in tanaguru.log
