### ISSUE TITLE
Polish charset 

### ISSUE THREAD

**Issue by trzepiz** [Tanaguru/Tanaguru#169]
Hi.
I have problem with Polish charset. 
MySQL - 5.7.26
Tanaguru database collation - utf8_general_ci 

Micha? - Michał

![tanaguru-charset-PL-User](https://user-images.githubusercontent.com/23279147/62876228-c7332180-bd24-11e9-8300-8c8e31013df3.png)

Wst**Ä**pnie - Wstępnie | obowi**Ä**zkowe - Obowiązkowe

![tanaguru-charset-PL-PDF](https://user-images.githubusercontent.com/23279147/62876233-c9957b80-bd24-11e9-9740-2650277c912f.png)

How to solve this problem ?

**Comment by fhalna** [comment]
Hello@trzepiz the tanaguru team is currently in vacation. So we will answer you next week !

**Comment by rcharre** [comment]
Hello,

Can you check you OS locales configuration ?

Regards,

Raphaël Charre - Tanaguru Team

**Comment by trzepiz** [comment]
Hi. 

**root@vps:~# locale**
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by trzepiz** [comment]
I test translate forgotten-password-page-I18N.properties file (UTF-8)

`forgotten-password.emailContent=<p>Witaj</p>\n<p>Otrzymaliśmy żądanie zresetowania hasła dla konta <strong>{0}</strong></p>`

In e-mail message I have: 
`OtrzymaliÅmy Å¼Ädanie zresetowania hasÅa dla konta xxxxxxx`

**Comment by rcharre** [comment]
Hi,

Can you try to set your locale to polish ? I had the same kind of issue with french characters.

Regards,

Raphaël Charre - Tanaguru Team

**Comment by trzepiz** [comment]
Hi. Now I have new VPS

```
LANG=pl_PL.UTF-8
LC_CTYPE="pl_PL.UTF-8"
LC_NUMERIC="pl_PL.UTF-8"
LC_TIME="pl_PL.UTF-8"
LC_COLLATE="pl_PL.UTF-8"
LC_MONETARY="pl_PL.UTF-8"
LC_MESSAGES="pl_PL.UTF-8"
LC_PAPER="pl_PL.UTF-8"
LC_NAME="pl_PL.UTF-8"
LC_ADDRESS="pl_PL.UTF-8"
LC_TELEPHONE="pl_PL.UTF-8"
LC_MEASUREMENT="pl_PL.UTF-8"
LC_IDENTIFICATION="pl_PL.UTF-8"
LC_ALL=
```
Problem is the same. But.. I open _es files and email work fine. 
in forgotten-password-page-I18N_es.properties:

`forgotten-password.emailContent=<p>Hola</p> <p>Tanaguru recibi\u00f3 una solicitud de restablecimiento de contrase\u00f1a de tu cuenta <strong>{0}</strong></p> <p>Si deseas restablecer la contrase\u00f1a, haz clic en el enlace de m\u00e1s abajo (o copia y pega la direcci\u00f3n URL en el navegador)\: <br/> <a href\="{1}"> restablecer mi contrase\u00f1a</a></p> <p>Este enlace te llevar\u00e1 a una p\u00e1gina donde puedes cambiar tu contrase\u00f1a. Escribe una contrase\u00f1a segura y juega con Tanaguru.</p> <p>Si no quieres cambiar tu contrase\u00f1a, por favor ignora este mensaje. Tu contrase\u00f1a no ser\u00e1 cambiada. En caso de problemas, por favor escr\u00edbenos a support@tanaguru.com</p> <p>El equipo de Tanaguru</p>`

In e-mail: 
```
Tanaguru recibió una solicitud de restablecimiento de contraseña de tu cuenta xxxxx

Si deseas restablecer la contraseña, haz clic en el enlace de más abajo (o copia y pega la dirección URL en el navegador):
restablecer mi contraseña

Este enlace te llevará a una página donde puedes cambiar tu contraseña. Escribe una contraseña segura y juega con Tanaguru.

Si no quieres cambiar tu contraseña, por favor ignora este mensaje. Tu contraseña no será cambiada. En caso de problemas, por favor escríbenos a support@tanaguru.com
```

So .. Can You give me solution "How to translate EN -> PL ? :)

**Comment by rcharre** [comment]
As you seen, in _es files unicode chararacter has been used.
So you may try to use those unicode characters or html ones.

Example : ę -> &eogon;

**Comment by trzepiz** [comment]
Hi, 
`forgotten-password.emailSubject=&eogon &eogon [Tanaguru] Zresetuj swoje hasło.`
Title in email: &eogon &eogon [Tanaguru] Zresetuj swoje hasÅo. 

But .. on site I have correct characters (UTF-8). 
```
forgotten-password.pageTitle = Nie pamiętasz hasła?
forgotten-password.h1 = Nie pamiętasz hasła?
```
![tanaguru-2](https://user-images.githubusercontent.com/23279147/63436301-bec79e80-c428-11e9-8031-d0f8a42b363f.png)

**Comment by rcharre** [comment]
Sorry for this, HTML code does not solve this problem. I juste tested unicode char and it seems to work.
For the same example : ę -> `\u0119`

**Comment by trzepiz** [comment]
Hi @rcharre 
So I have to prepare all files in UTF-8, but convert Polish characters to Unicode? :/
Why on site all work OK but not in database and e-mail?

**Comment by rcharre** [comment]
Hi,
Indeed, this is what has been done for _fr _es and _de for now.
I am affraid i could not tell you why encoding issues are occurring in mails and database.

https://github.com/eclipse/smarthome/issues/2639 this may answer.

**Comment by trzepiz** [comment]
Have You any fast solution to convert all files, all polish characters  to Unicode ?

**Comment by dzc34** [comment]
[native2ascii.net](https://native2ascii.net/) allow you to convert national language characters to and from their Unicode equivalents in plain ASCII text.

#### UTF8 to ASCII with Unicode escapes
Converts a file encoded in UTF8 to a file in ASCII with Unicode escapes.
```bash
# native2ascii from JDK (no longer available since JDK9)
native2ascii -encoding utf8 example_utf8.txt example_ISO-8859-1.txt

# UTF8 to ASCII with Unicode escapes 
apt install uni2ascii
uni2ascii -q -a U example_utf8.txt > example_ASCII.txt
```

#### ASCII with Unicode escapes to UTF8
Converts a file encoded in ASCII with Unicode escapes to a file in UTF8 character encoding.
```bash
# native2ascii from JDK (no longer available since JDK9)
native2ascii -encoding utf8 -reverse example.propertie   example.reverse.utf8.txt

# ASCII with Unicode escapes to UTF8
apt install uni2ascii
ascii2uni -q -a U example_ASCII.txt > example_utf8.txt
```

**Comment by dzc34** [comment]
for convert all files in a i18n directory:
```
mkdir ../newFiles/
find -name "*I18N_pl.properties" -type f -exec bash -c "uni2ascii -q -a U  {} > ../newFiles/{}" \;
cp -v  ../newFiles/* ./
rm -r ../newFiles/
```

**Comment by trzepiz** [comment]
Thanks @rcharre @dzc34.
