### ISSUE TITLE
Tests for WCAG 2.1

### ISSUE THREAD

**Issue by zwiastunsw** [Tanaguru/Tanaguru#170]
Whether and when it is planned to add tests to WCAG 2.1

**Comment by fhalna** [comment]
Hi,
We are working on wcag 2.1 tests in the tanaguru extension. After validation we will implement the new test in Tanaguru engine. https://github.com/Tanaguru/webextension

We are also waiting the new version of RGAA v4 (compliant to Wcag 2.1).
