### ISSUE TITLE
Default and Max Crawl limits

### ISSUE THREAD

**Issue by trzepiz** [Tanaguru/Tanaguru#171]
Hi, 
Is it possible to change the default and maximum settings for Crawl limits in "Audit Full-Site" ?

**Comment by rcharre** [comment]
Hi,

In <app directory>/WEb-INF/lib you can extract tanaguru-resources-<version> and edit beans-crawler.xml. Here you can change the crawl limit of document, the maximum depth, the maximum duration.

However i recommend you to not crawl a huge number of page if they use the same structure, in this case a group of page audit will be better.

Regards,

Raphaël Charre - Tanaguru Team

**Comment by trzepiz** [comment]
Thanks !
