### ISSUE TITLE
Source code - Incorrect [Line_X]

### ISSUE THREAD

**Issue by trzepiz** [Tanaguru/Tanaguru#172]
Hi,
I have problem with correct [Line]. I test on your demo site. Problem is the same. 

Test: https://my.tanaguru.com/home/contract/page-result.html?wr=372828
Test: 10.4.1 
Problem: `<h3> <a href="-Cadres-.html">Th&eacute;matique 1&nbsp;: Cadres</a> </h3> Line 65`

But in html code in line 65 I have
https://my.tanaguru.com/home/contract/source-code-page.html?wr=372828#line65

In other my tests many lines is +1 .. problem in Line 60 in source is 61 ..

**Comment by rcharre** [comment]
Hi,

Thank you for reporting this issue. I worked on it and the fix will be in the next release (6.1.0).

Regards,

Raphaël Charre - Tanaguru Team
