### ISSUE TITLE
The assisted audit - not working

### ISSUE THREAD

**Issue by zwiastunsw** [Tanaguru/Tanaguru#174]
I want to do an assisted audit. According to the instructions (https://tanaguru.readthedocs.io/en/develop/userdoc-assisted-audit/), I first performed an audit of the website. Then I started the manual audit. Unfortunately, the buttons do not work:   Apply all the auto passed results, Apply all the auto failed results, Apply all the auto not aplicable. 
<img width="960" alt="2019-09-17_11-56-58" src="https://user-images.githubusercontent.com/29527200/65153866-c891f100-da2a-11e9-8937-70f0da35923a.png">

**Comment by rcharre** [comment]
Hi,

Those buttons auto feel the differents fields for tests validation then you must save it in order to see changes applied in the page and charts.

Regards,

Raphaël Charre - Tanaguru Team
