### ISSUE TITLE
Theme 3 : Colours - not tested

### ISSUE THREAD

**Issue by trzepiz** [Tanaguru/Tanaguru#175]
Hi, 
Why Colours is not tested ? 
Link to test: https://my.tanaguru.com/home/contract/page-result.html?wr=375651&cr=943&lang=en

I have many contrast error, but Tanaguru not reported them. 
![Screenshot_2019-09-23 Strony internetowe - Administracja Joomla - BlueCoyote](https://user-images.githubusercontent.com/23279147/65430902-f4411c80-de18-11e9-8f4b-e271a093ea1e.png)

**Comment by rcharre** [comment]
Hi,

Thanks for your report, this issue will be solved in the next release ! :)

Regards,

Raphaël Charre - Tanaguru Team
