### ISSUE TITLE
6.1.0 or 6.1.0-fixed

### ISSUE THREAD

**Issue by trzepiz** [Tanaguru/Tanaguru#176]
Hi, 
What is the difference between tanaguru-6.1.0.i386.tar.gz and tanaguru-6.1.0-fixed.i386.tar.gz ?
http://download.tanaguru.org/Tanaguru/

I noticed that in the file tanaguru-6.1.0-fixed.i386.tar.gz is folder tanaguru-7.0.0-SNAPSHOT.i386 (not 6.x)

**Comment by rcharre** [comment]
Hi,

Version 6.1.0-fixed includes some fixes that we didn't see when 6.1.0 was released. 
That include a dependency conflict that occurs on some servers. A fix for site parameters regex (include and exlude urls), ...

Some of these causing issues on production environnement, I released this version during 7.0.0 developement.

Regards,
