### ISSUE TITLE
Documentation obsolète

### ISSUE THREAD

**Issue by AlexandreCantin** [Tanaguru/Tanaguru#177]
Bonjour,

Je souhaiterai utiliser Tanaguru (en mode CLI) pour un projet personnel mais la documentation (https://tanaguru.readthedocs.io/en/develop/install-cli-doc/) n'est plus à jour (elle fait référence des fichiers qui n'existent plus comme `install/engine/sql/tanaguru-20-create-tables.sql` - datant sûrement sur la version 3 de Tanaguru).
Malheureusement, il n'y a plus de dossier Docker dans le projet... ce qui laisse supposer qu'il contenait aussi des fichiers obsolètes 😢

Du coup, j'aimerai savoir s'il existe-t-il des ressources plus à jour ? (Ou alors, une dockerisation clé en main ? ce qui serait le Saint-Graal 😄)

Merci d'avance pour votre réponse et bonne journée,
Alexandre

**Comment by rcharre** [comment]
Bonjour,

En effet j'ai oublié de mettre à jour la partie CLI de la doc. Je viens de faire la modification ([https://tanaguru.readthedocs.io/en/latest/install-cli-doc/](https://tanaguru.readthedocs.io/en/latest/install-cli-doc/)).
Toute la gestion de la base de données est intégrée dans le projet par l'intermédiaire de Liquibase depuis les dernières versions.

Il existe des images docker à jour, cependant elles sont privées, si vous voulez en savoir plus, veuillez contacter support@tanaguru.com.

J’espère avoir répondu à vos questions, je vous souhaite une bonne journée :)

Raphaël CHARRE - Equipe Tanaguru
