### ISSUE TITLE
Exclude subdomain

### ISSUE THREAD

**Issue by i-tpl** [Tanaguru/Tanaguru#178]
Hi,

How to exclude whole subdomain for full-site audit?
Let's say I want to audit http://example.com and exclude http://subdomain.example.com.
I've tried to paste text "subdomain.example.com" (or regex ".*subdomain\.example\.com.*" to field "Exclude urls containing" but it doesn't work. Do I need to paste whole URLs, or is it another way to define some kind of pattern for excluding URLs?

**Comment by rcharre** [comment]
Hi,

The field to exclude or include url works with regular expression, in your case you need to escape special characters like this : \.subdomain\.example\.com

Let me know if it is ok for you.

Regards,

Raphaël Charre - Tanaguru Team

**Comment by i-tpl** [comment]
I was using version 6.1.0 and I see URL exclusions was fixed in 6.1.0-fixed as stated in #176 .
Changed to 6.1.0-fixed and everything is working fine.
Thanks for your help!
