### ISSUE TITLE
Recommended VPS for Tanaguru

### ISSUE THREAD

**Issue by trzepiz** [Tanaguru/Tanaguru#181]
Hi. 
I'm testing Tanaguru on Contabo VPS. I have https://contabo.com/?show=configurator&vserver_id=221

Tanaguru on this configuration is very slow. What is the VPS recommended by you?
Maybe you have any tips how to speed up Tomcat?
Which is more important CPU or RAM?

**Comment by rcharre** [comment]
Hi,

For our servers I am using 8GB of RAM and 2CPU, so the system configuration you sent is OK.
Can you eplain me what are you trying to audit and with what configuration ?

Regards,

Raphael CHARRE - Tanaguru Team

**Comment by trzepiz** [comment]
I tested now on Virtualbox and Ubuntu 18.04 on my PC.
Tanaguru and Tomcat work very fast. Problem is with Contabo (I think).
