### ISSUE TITLE
Tanaguru and RGAA 4.0

### ISSUE THREAD

**Issue by zwiastunsw** [Tanaguru/Tanaguru#193]
I will ask you again. If and when you can expect Tanagur version for RGAA 4.0

**Comment by rcharre** [comment]
Hello,

I just released the new version of Tanaguru : Tanaguru2020.
You can find it here : 
- https://github.com/Tanaguru/tanaguru2020-engine for the server side
- https://github.com/Tanaguru/tanaguru2020-webapp for the client side

We also have docker image only available for our clients, if you are interested in this I invite you to send us a mail at : support@tanaguru.com

The new version come with a free test set corresponding to wcag, Rgaa4 is for the moment reserved to our clients.

Thanks for your interest.

Raphaël CHARRE - Tanaguru team
