### ISSUE TITLE
Create 2 different queues for page-audits & site-audits

### ISSUE THREAD

**Issue by mfaure** [Tanaguru/Tanaguru#79]
Page-audits to be run must not wait for site-audits to finish or they are stuck potentially for hours, waiting the site-audit to terminate.

Typical case: user A launches 10 site-audits on 10'000 pages each. One minute after, user B runs a page-audit, that goes asynchronous, and will be actually run when the site-audits are finished.

Said differently, create 2 different queues:

* one for the page-audit / file-audit
* another one for site-audit / scenario-audit

**Comment by jkowalczyk** [comment]
Unable to reproduce, sorry :)
