### ISSUE TITLE
Option not enter "http: //"

### ISSUE THREAD

**Issue by Lapeze** [Tanaguru/Tanaguru#99]
I would not need to enter "http://" in the URL input

if I edit url manualy, I do not think necessarily to enter http:// and it bothers me to have a mistake for it

![Caption above](https://cloud.githubusercontent.com/assets/9350147/6128433/10ef2648-b136-11e4-83a0-ddb946ff4619.png)

Is it possible that the "http: //" is added automatically when it is not present?

**Comment by mkebri** [comment]
Considering the difference between http:// and https:// we would keep this option unchanged.
